### ISSUE TITLE
Invalid docker-compose

### ISSUE THREAD

**Issue by SebastianBorges** [Fiware/tutorials.Historic-Context#13]
Hi,
i am getting this error when executing ./services mongodb (postgres, mysql, multiple):

`ERROR: The Compose file './docker-compose/multiple.yml' is invalid because:
services.draco.expose is invalid: should be of the format 'PORT[/PROTOCOL]'
services.mongo-db.expose is invalid: should be of the format 'PORT[/PROTOCOL]'
services.mysql-db.expose is invalid: should be of the format 'PORT[/PROTOCOL]'
services.postgres-db.expose is invalid: should be of the format 'PORT[/PROTOCOL]'
services.tutorial.expose is invalid: should be of the format 'PORT[/PROTOCOL]'
services.tutorial.expose is invalid: should be of the format 'PORT[/PROTOCOL]'
services.draco.ports contains an invalid type, it should be a number, or an object
services.iot-agent.ports contains an invalid type, it should be a number, or an object
services.iot-agent.ports contains an invalid type, it should be a number, or an object
services.mongo-db.ports contains an invalid type, it should be a number, or an object
services.mysql-db.ports contains an invalid type, it should be a number, or an object
services.orion.ports contains an invalid type, it should be a number, or an object
services.postgres-db.ports contains an invalid type, it should be a number, or an object
services.tutorial.ports contains an invalid type, it should be a number, or an object
services.tutorial.ports contains an invalid type, it should be a number, or an object
services.tutorial.expose value ['', ''] has non-unique elements
services.iot-agent.ports value [':', ':'] has non-unique elements
services.tutorial.ports value [':', ':'] has non-unique elements
`

./services start is working.

**Comment by jason-fox** [comment]
What environment are you using? The docker-compose command is failing to recognize the `.env` file so it is not finding the ports and what have you. Adding :

```console
export $(cat .env | grep "#" -v)
```

should help. I had the same issue with the GitHub Action for sanity testing (which is why `start` works)
